# Generated by Django 3.2.16 on 2022-11-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
